[project]
name = "batch-get-imdbid"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bs4>=0.0.2",
    "requests>=2.32.5",
    "simple-term-menu>=1.6.6",
]
